### ISSUE TITLE
Add Support for Other PDF Preview Applications

### ISSUE THREAD

**Issue by xuchef** [HusseinElguindi/tex-live-preview#1]
Dear Elguindi,

I hope this message finds you well and you are having a wonderful winter break so far! The snowflakes really are beautiful this time of year. You have worked so hard over the last 4 months helping me and other students, often hosting office hours at odd times of day. No one deserves to lay back, relax, and watch Young Sheldon with their family more so than you.

Thank you for being an amazing professor! The mark you have left on me is indelible.

P.S. please add a config file or command so that this program can be used with PDF viewers other than Skim.

Best regards,
Michael Xu

**Comment by HusseinElguindi** [comment]
Hello Michael Xu, 

Thank you for the kind words, I hope you are well too. Unfortunately, I will not be continuing this project as there is a more idiomatic alternative. That is `latexmk`. 

`latexmk` has a preview feature, use it by running the command `latexmk -pvc -f main.tex`. It will automatically compile on any changes to your project or included source files. You can then open the `.dvi` file (unless`-pdf` is also specified, then there will be a`.pdf` file) in any viewer of your choice. A viewer which supports automatic reload is best, I suggest Skim for Mac systems.

Hussein Elguindi.
