### ISSUE TITLE
I am very angry at your program because it has bugs.

### ISSUE THREAD

**Issue by xuchef** [HusseinElguindi/tex-live-preview#2]
If your first instinct is "Uhhh he's probably not using it right," find yourself a doctor. A real one. Not some PhD.

The user is always right!!!

I ask kindly for you to please fix your program.

The issue that I have found at the moment is that it does not work unless I specify an absolute path starting with `~/`. Garbage.

Consider adding the following gif to the README of your project:
![image](https://user-images.githubusercontent.com/61663933/209294613-ed8eb310-cdfa-4e75-bf06-4932c1dd56d3.gif)

**Comment by HusseinElguindi** [comment]
I appreciate your constructive feedback, Michael. I have not had issues regarding relative paths. However, as I mentioned in Issue #1, this project will not be continued as there is a better idiomatic alternative. Please read the details there (#1).
